# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Table.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Table(object):
    group = str()

    def setupUi(self, Table, group):
        Table.setObjectName("Table")
        Table.resize(806, 675)
        Table.setTabletTracking(False)
        Table.setAcceptDrops(False)
        Table.setLayoutDirection(QtCore.Qt.LeftToRight)
        Table.setAutoFillBackground(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(Table)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnDelete = QtWidgets.QPushButton(Table)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 1, 3, 1, 1)
        self.btnUpdate = QtWidgets.QPushButton(Table)
        self.btnUpdate.setObjectName("btnUpdate")
        self.gridLayout.addWidget(self.btnUpdate, 1, 2, 1, 1)
        self.btnClose = QtWidgets.QPushButton(Table)
        self.btnClose.setObjectName("btnClose")
        self.gridLayout.addWidget(self.btnClose, 1, 4, 1, 1)
        self.btnInsert = QtWidgets.QPushButton(Table)
        self.btnInsert.setObjectName("btnInsert")
        self.gridLayout.addWidget(self.btnInsert, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Table)
        self.tableWidget.setMinimumSize(QtCore.QSize(2, 0))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(190)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(45)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(45)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.group = group

        self.retranslateUi(Table, self.group)
        QtCore.QMetaObject.connectSlotsByName(Table)

    def retranslateUi(self, Table, group):
        _translate = QtCore.QCoreApplication.translate
        Table.setWindowTitle(_translate("Table", "Список абитуриентов " + self.group))
        self.btnDelete.setText(_translate("Table", "Удалить"))
        self.btnUpdate.setText(_translate("Table", "Изменить"))
        self.btnClose.setText(_translate("Table", "Закрыть"))
        self.btnInsert.setText(_translate("Table", "Добавить"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Table", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Table", "ФИО"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Table", "Общее кол-во баллов"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Table", "Оригинал"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Table = QtWidgets.QWidget()
    ui = Ui_Table()
    ui.setupUi(Table)
    Table.show()
    sys.exit(app.exec_())
